export enum actionTypes {
    GET_PROFILE_START = 'GET_PROFILE_START',
    GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE',

    UPDATE_PROFILE_START = 'UPDATE_PROFILE_START',
    UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE',

    GET_AVATAR_START = 'GET_AVATAR_START',
    GET_AVATAR_SUCCESS = 'GET_AVATAR_SUCCESS',
    GET_AVATAR_FAILURE = 'GET_AVATAR_FAILURE',

    CLEAR_ERROR = 'CLEAR_ERROR',

    CLEAR_ALL_USER = 'CLEAR_ALL_USER',
}
