export enum actionTypes {
    CLEAR_ALL_AUTH = 'CLEAR_ALL_AUTH',

    REGISTER_START = 'REGISTER_START',
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_FAILURE = 'REGISTER_FAILURE',

    LOGIN_START = 'LOGIN_START',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',

    CHECK_STATE = 'CHECK_STATE',
}
