export enum actionTypes {
    CLEAR_INDICATION = 'CLEAR_INDICATION',

    CLEAR_ALL_TASK = 'CLEAR_ALL_TASK',

    CREATE_TASK_START = 'CREATE_TASK_START',
    CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS',
    CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE',

    FETCH_TASKS_START = 'FETCH_TASKS_START',
    FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE',

    UPDATE_TASK_START = 'UPDATE_TASK_START',
    UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE',

    DELETE_TASK_START = 'DELETE_TASK_START',
    DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS',
    DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE',

    DELETE_TASKS_COMPLETED_START = 'DELETE_TASKS_COMPLETED_START',
    DELETE_TASKS_COMPLETED_SUCCESS = 'DELETE_TASKS_COMPLETED_SUCCESS',
    DELETE_TASKS_COMPLETED_FAILURE = 'DELETE_TASKS_COMPLETED_FAILURE',

    SELECT_DATE = 'SELECT_DATE',
    CLEAR_SELECTED_DATE = 'CLEAR_SELECTED_DATE',
}
